# unit_test/_venv_guard.py
"""Offline guard for isolated-plugin venvs during the unit suite.

A fresh (per-session) GRAPHYN_HOME makes the plugin bootstrap install every
bundled plugin; for ``runtime = "isolated"`` plugins the loader calls
``PluginVenvManager.ensure`` which would build venvs and pip-install multi-GB
ML stacks (torch / ultralytics) over the network. For the *session* venvs dir
only, ``ensure`` is replaced to return the existing (symlinked, developer-built)
venv python untouched, or the host interpreter when no venv was ever built —
enough for registration / validation tests. Venv-manager tests that pass an
explicit ``base_dir`` are unaffected.

Installed in-process by ``unit_test/conftest.py`` and in CLI/API subprocesses
through a ``sitecustomize`` shim on PYTHONPATH (host interpreter only).
Set ``GRAPHYN_TEST_BUILD_VENVS=1`` to restore real behaviour.
"""
from __future__ import annotations

import functools
import os
import sys
from pathlib import Path

ENV_DIR = "GRAPHYN_TEST_VENV_GUARD_DIR"
ENV_PREFIX = "GRAPHYN_TEST_VENV_GUARD_PREFIX"


def install(session_venvs: Path) -> None:
    if os.environ.get("GRAPHYN_TEST_BUILD_VENVS", "").strip().lower() in ("1", "true", "yes"):
        return
    from app.core.plugins.venv_manager import PluginVenvManager

    if getattr(PluginVenvManager.ensure, "_graphyn_test_guard", False):
        return
    real_ensure = PluginVenvManager.ensure
    root = Path(session_venvs).resolve()

    @functools.wraps(real_ensure)
    def _ensure(self, plugin_name, requirements, **kwargs):
        try:
            under_session = Path(self._base).resolve() == root
        except OSError:
            under_session = False
        if under_session:
            py = self.python_bin(plugin_name)
            return py if py.exists() else Path(sys.executable)
        return real_ensure(self, plugin_name, requirements, **kwargs)

    _ensure._graphyn_test_guard = True  # type: ignore[attr-defined]
    PluginVenvManager.ensure = _ensure  # type: ignore[method-assign]


def install_from_env() -> None:
    """Entry point for the sitecustomize shim (subprocesses)."""
    raw = os.environ.get(ENV_DIR, "").strip()
    if not raw or os.environ.get(ENV_PREFIX, "") != sys.prefix:
        return
    try:
        install(Path(raw))
    except Exception:  # pragma: no cover — never break a subprocess start
        pass


SITECUSTOMIZE_SRC = '''\
# Generated by unit_test/conftest.py for the test session only.
try:
    from unit_test._venv_guard import install_from_env as _g
    _g()
except Exception:
    pass
'''
