"""EnvironmentSimulatorNode — simulate physical acoustic environments.

Convolves audio with a room impulse response (RIR) generated by pyroomacoustics,
then optionally adds background noise at a configurable SNR.

Presets:
    room    — generic small room (5×4×3 m, RT60=0.4 s)
    car     — car interior (2×1.5×1.2 m, RT60=0.15 s)
    office  — open-plan office (10×8×3 m, RT60=0.6 s)
    outdoor — anechoic / outdoor (large room, RT60=0.05 s)
    custom  — use room_dimensions, rt60, mic_position, source_position directly
"""
from __future__ import annotations

import copy
import logging
from typing import ClassVar

import numpy as np

from app.core.nodes.base import Node
from app.core.nodes.config import NodeConfig
from app.core.nodes.metadata import NodeMetadata
from app.core.nodes.ports import InputPort, OutputPort
from app.models.audio_sample import AudioSample

log = logging.getLogger(__name__)

# ── preset definitions ────────────────────────────────────────────────────────
_PRESETS: dict[str, dict] = {
    "room": {
        "room_dimensions": [5.0, 4.0, 3.0],
        "rt60": 0.4,
        "mic_position": [2.5, 2.0, 1.5],
        "source_position": [1.0, 1.0, 1.5],
    },
    "car": {
        "room_dimensions": [2.0, 1.5, 1.2],
        "rt60": 0.15,
        "mic_position": [1.0, 0.75, 0.9],
        "source_position": [0.3, 0.75, 0.9],
    },
    "office": {
        "room_dimensions": [10.0, 8.0, 3.0],
        "rt60": 0.6,
        "mic_position": [5.0, 4.0, 1.5],
        "source_position": [2.0, 2.0, 1.5],
    },
    "outdoor": {
        "room_dimensions": [50.0, 50.0, 10.0],
        "rt60": 0.05,
        "mic_position": [25.0, 25.0, 1.5],
        "source_position": [20.0, 25.0, 1.5],
    },
}


class EnvironmentSimulatorNode(Node):
    """Simulate physical acoustic environments via room impulse response convolution.

    Uses pyroomacoustics to generate a RIR for the configured room geometry,
    then convolves the input audio with it. Optionally adds Gaussian noise
    at a specified SNR.

    Config:
        preset (str): "room" | "car" | "office" | "outdoor" | "custom"
        room_dimensions (list): [x, y, z] in metres (custom preset only)
        rt60 (float): reverberation time in seconds (custom preset only)
        mic_position (list): [x, y, z] microphone position in metres
        source_position (list): [x, y, z] source position in metres
        snr_db (float): SNR for added Gaussian noise; 0 = no noise (default 0.0)
        copies_per_sample (int): number of augmented copies per input sample (default 1)
        max_rir_length_ms (float): truncate RIR to this length in ms (default 500)
    """

    node_type: ClassVar[str] = "environment_simulator"

    metadata: ClassVar[NodeMetadata] = NodeMetadata(
        node_type="environment_simulator",
        label="Environment Simulator",
        description=(
            "Simulate physical acoustic environments via room impulse response "
            "convolution (pyroomacoustics). Presets: room, car, office, outdoor, custom."
        ),
        category="Enhancement",
        version="1.0.0",
        tags=["audio", "simulation", "reverb", "rir", "pyroomacoustics", "augmentation"],
        requires_gpu=False,
        supports_cpu=True,
        supports_edge=False,
        deterministic=True,
        cacheable=True,
        streaming_support=False,
        realtime_support=False,
    )

    input_ports: ClassVar[dict[str, InputPort]] = {
        "input": InputPort(
            name="input",
            data_type=list[AudioSample],
            cardinality="single",
            required=True,
            description="Clean audio samples to simulate",
        )
    }

    output_ports: ClassVar[dict[str, OutputPort]] = {
        "output": OutputPort(
            name="output",
            data_type=list[AudioSample],
            description="Simulated audio samples with room_simulation metadata",
        )
    }

    class Config(NodeConfig):
        preset: str = "room"                        # "room"|"car"|"office"|"outdoor"|"custom"
        room_dimensions: list = [5.0, 4.0, 3.0]    # metres [x, y, z]
        rt60: float = 0.4                           # reverberation time (seconds)
        mic_position: list = [2.5, 2.0, 1.5]       # [x, y, z]
        source_position: list = [1.0, 1.0, 1.5]    # [x, y, z]
        snr_db: float = 0.0                         # 0 = no noise added
        copies_per_sample: int = 1
        # NOTE: copies_per_sample > 1 only produces diverse augmentations when
        # snr_db > 0 (noise is randomised per copy). With snr_db=0 all copies
        # are acoustically identical (same deterministic RIR convolution).
        max_rir_length_ms: float = 500.0            # truncate RIR to this length
        preserve_length: bool = False               # if True, trim output to original length

    # ── setup: check pyroomacoustics once ─────────────────────────────────────

    def setup(self) -> None:
        try:
            import pyroomacoustics  # type: ignore  # noqa: F401
        except ImportError:
            raise ImportError(
                "EnvironmentSimulatorNode: 'pyroomacoustics' required. "
                "Install with: pip install pyroomacoustics>=0.7"
            )

    # ── SISO process ──────────────────────────────────────────────────────────

    def process(self, samples: list[AudioSample]) -> list[AudioSample]:
        output: list[AudioSample] = []

        for sample in samples:
            for _ in range(max(1, self.config.copies_per_sample)):
                simulated = self._simulate(sample)
                output.append(simulated)

        return output

    # ── simulation ────────────────────────────────────────────────────────────

    def _simulate(self, sample: AudioSample) -> AudioSample:
        import pyroomacoustics as pra  # type: ignore

        # Resolve preset geometry
        preset = self.config.preset
        if preset == "custom":
            dims = list(self.config.room_dimensions)
            rt60 = float(self.config.rt60)
            mic_pos = list(self.config.mic_position)
            src_pos = list(self.config.source_position)
        elif preset in _PRESETS:
            p = _PRESETS[preset]
            dims = list(p["room_dimensions"])
            rt60 = float(p["rt60"])
            mic_pos = list(p["mic_position"])
            src_pos = list(p["source_position"])
        else:
            raise ValueError(
                f"EnvironmentSimulatorNode: unknown preset '{preset}'. "
                "Choose from: room, car, office, outdoor, custom"
            )

        y = sample.data.astype(np.float32)
        sr = sample.sample_rate

        # Clamp positions to be inside room
        mic_pos = [min(mic_pos[i], dims[i] - 0.1) for i in range(3)]
        src_pos = [min(src_pos[i], dims[i] - 0.1) for i in range(3)]

        # Build room and compute RIR
        e_absorption, max_order = pra.inverse_sabine(rt60, dims)
        room = pra.ShoeBox(
            dims,
            fs=sr,
            materials=pra.Material(e_absorption),
            max_order=max_order,
        )
        room.add_source(src_pos, signal=y)
        mic_array = np.array(mic_pos).reshape(3, 1)
        room.add_microphone(mic_array)
        room.simulate()

        # Extract simulated signal (first mic, first source)
        y_sim = room.mic_array.signals[0].astype(np.float32)

        # Truncate to original length + reverb tail
        max_rir_samples = int(self.config.max_rir_length_ms / 1000.0 * sr)
        max_len = len(y) + max_rir_samples
        y_sim = y_sim[:max_len]

        # Optionally trim to original length (discards reverb tail)
        if self.config.preserve_length:
            y_sim = y_sim[:len(y)]

        # Normalise to prevent clipping
        peak = np.max(np.abs(y_sim))
        if peak > 1e-6:
            y_sim = y_sim / peak * np.max(np.abs(y))

        # Add Gaussian noise at specified SNR
        if self.config.snr_db > 0:
            y_sim = self._add_noise(y_sim, self.config.snr_db)

        new_sample = copy.deepcopy(sample)
        new_sample.data = y_sim.astype(np.float32)
        new_sample.metadata.update({
            "room_simulation": {
                "preset": preset,
                "room_dimensions": dims,
                "rt60": rt60,
                "mic_position": mic_pos,
                "source_position": src_pos,
                "snr_db": self.config.snr_db,
            }
        })
        return new_sample

    def _add_noise(self, y: np.ndarray, snr_db: float) -> np.ndarray:
        """Add Gaussian noise at the specified SNR in dB.

        Uses self.seed for reproducibility so deterministic=True holds
        when the same seed is used.
        """
        signal_power = np.mean(y ** 2)
        if signal_power < 1e-10:
            return y
        noise_power = signal_power / (10 ** (snr_db / 10.0))
        rng = np.random.default_rng(seed=self.seed)
        noise = rng.normal(0, np.sqrt(noise_power), len(y))
        return (y + noise).astype(np.float32)
