#!/usr/bin/env python3
"""Run the packaged model on real audio files.

Generated by the Graphyn ``deployment_packager`` node. The feature extraction
below mirrors the platform's Feature Frontend + Dataset Builder exactly; the
parameters come from ``preprocessing.json`` (the source training run's own
configuration), so audio is turned into the same tensor the model saw during
training.

Usage::

    pip install -r requirements.txt
    python run_inference.py clip.wav                 # top-3 labels
    python run_inference.py a.wav b.wav --top-k 6 --json
    python run_inference.py --describe               # model tensors + preprocessing
    python run_inference.py --features x.npy --json  # pre-computed (T, F) features

Runtime: ``ai_edge_litert`` / ``tflite_runtime`` when installed, else
``tensorflow.lite``. WAV decoding + features need ``librosa`` (pinned in
requirements.txt to the version the model was trained with).
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent


# ── package files ─────────────────────────────────────────────────────────────

def load_preprocessing(path: Path | None = None) -> dict:
    """Return preprocessing.json as a dict (empty dict when the file is missing)."""
    p = Path(path) if path else HERE / "preprocessing.json"
    if not p.is_file():
        return {}
    return json.loads(p.read_text(encoding="utf-8"))


def load_labels(cfg: dict, path: Path | None = None) -> list[str]:
    """Class names in model output order (labels.txt wins over preprocessing.json)."""
    p = Path(path) if path else HERE / "labels.txt"
    if p.is_file():
        rows = [ln.strip() for ln in p.read_text(encoding="utf-8").splitlines()]
        rows = [r for r in rows if r]
        if rows:
            return rows
    return [str(x) for x in (cfg.get("labels") or [])]


# ── audio + features (mirror of feature_frontend + dataset_builder) ───────────

def load_audio(path: str | Path) -> tuple[np.ndarray, int]:
    """Decode a file like dataset_ingest: native rate, mixed down to mono, float32."""
    import librosa

    y, sr = librosa.load(str(path), sr=None, mono=True)
    return y, int(sr)


def _normalize(x: np.ndarray) -> np.ndarray:
    """Per-utterance z-score over the whole matrix (feature_frontend._normalize)."""
    mean = np.mean(x)
    std = np.std(x)
    if std <= 1e-8:
        return x
    return (x - mean) / std


def _append_deltas(features: np.ndarray, delta: bool, delta_delta: bool) -> np.ndarray:
    import librosa

    parts = [features]
    d1 = librosa.feature.delta(features).astype(np.float32)
    if delta:
        parts.append(d1)
    if delta_delta:
        parts.append(librosa.feature.delta(d1).astype(np.float32))
    return np.concatenate(parts, axis=0)


def _pad_or_truncate(data: np.ndarray, length: int) -> np.ndarray:
    """Zero-pad at the end / keep the first ``length`` frames on the time axis."""
    if data.ndim == 1:
        data = data[:, np.newaxis]
    t, f = data.shape
    if t == length:
        return data
    if t > length:
        return data[:length, :]
    pad = np.zeros((length - t, f), dtype=np.float32)
    return np.concatenate([data, pad], axis=0)


def extract_features(y: np.ndarray, sr: int, cfg: dict) -> np.ndarray:
    """Waveform → (T, F) float32 feature matrix, exactly as in training.

    Steps (all parameters from ``cfg["features"]`` / ``cfg["frames"]``):
    resample to ``sample_rate`` (librosa default resampler) → feature
    extraction → optional delta stacking → per-utterance z-score →
    (F, T) → (T, F) → Feature Frontend ``fixed_length`` → Dataset Builder
    ``fixed_length`` (pad with zeros at the end / truncate).
    """
    import librosa

    fc = dict(cfg.get("features") or {})
    frames = dict(cfg.get("frames") or {})
    ftype = str(fc.get("feature_type") or "log_mel").lower()
    target_sr = int(fc.get("sample_rate") or sr)
    n_fft = int(fc.get("n_fft", 512))
    hop = int(fc.get("hop_length", 160))
    win = int(fc.get("win_length", 400))
    n_mels = int(fc.get("n_mels", 80))
    fmin = float(fc.get("fmin", 0.0) or 0.0)
    fmax = fc.get("fmax")
    fmax = float(fmax) if fmax not in (None, "") else None
    center = bool(fc.get("center", True))
    delta = bool(fc.get("delta", False))
    delta_delta = bool(fc.get("delta_delta", False))

    y = np.asarray(y).astype(np.float32)
    if sr != target_sr:
        y = librosa.resample(y=y, orig_sr=sr, target_sr=target_sr)
        sr = target_sr

    if ftype == "log_mel":
        mel = librosa.feature.melspectrogram(
            y=y, sr=sr, n_fft=n_fft, hop_length=hop, win_length=win,
            n_mels=n_mels, fmin=fmin, fmax=fmax, center=center,
        )
        if bool(fc.get("log_scale", True)):
            feats = librosa.power_to_db(mel, ref=np.max).astype(np.float32)
        else:
            feats = mel.astype(np.float32)
        if delta or delta_delta:
            feats = _append_deltas(feats, delta, delta_delta)
    elif ftype == "mfcc":
        feats = librosa.feature.mfcc(
            y=y, sr=sr, n_mfcc=int(fc.get("n_mfcc", 13)), n_fft=n_fft,
            hop_length=hop, win_length=win, n_mels=n_mels, fmin=fmin,
            fmax=fmax, center=center,
        ).astype(np.float32)
        if delta or delta_delta:
            feats = _append_deltas(feats, delta, delta_delta)
    elif ftype == "spectrogram":
        spec = np.abs(librosa.stft(y, n_fft=n_fft, hop_length=hop, win_length=win, center=center))
        if bool(fc.get("log_scale", True)):
            spec = librosa.amplitude_to_db(spec, ref=np.max)
        feats = spec.astype(np.float32)
    elif ftype == "chroma":
        feats = librosa.feature.chroma_stft(
            y=y, sr=sr, n_fft=n_fft, hop_length=hop, center=center,
        ).astype(np.float32)
    elif ftype == "zcr":
        feats = librosa.feature.zero_crossing_rate(
            y, frame_length=win, hop_length=hop, center=center,
        ).astype(np.float32)
    elif ftype == "spectral_centroid":
        feats = librosa.feature.spectral_centroid(
            y=y, sr=sr, n_fft=n_fft, hop_length=hop, win_length=win, center=center,
        ).astype(np.float32)
    elif ftype == "spectral_rolloff":
        feats = librosa.feature.spectral_rolloff(
            y=y, sr=sr, n_fft=n_fft, hop_length=hop, win_length=win, center=center,
        ).astype(np.float32)
    elif ftype == "raw":
        feats = y[np.newaxis, :].astype(np.float32)
    else:
        raise ValueError(f"unsupported feature_type {ftype!r} in preprocessing.json")

    if bool(fc.get("normalize", True)) and ftype != "raw":
        feats = _normalize(feats)
    if feats.ndim == 2:
        feats = feats.T  # (F, T) → (T, F)

    ff_len = int(fc.get("fixed_length") or 0)
    if ff_len > 0 and feats.ndim == 2:
        feats = _pad_or_truncate(feats, ff_len)

    if feats.ndim == 1:
        feats = feats[:, np.newaxis]
    elif feats.ndim > 2:
        feats = feats.reshape(feats.shape[0], -1)
    fixed = int(frames.get("fixed_length") or 0)
    if fixed > 0:
        feats = _pad_or_truncate(feats, fixed)
    return feats.astype(np.float32)


def preprocess_file(path: str | Path, cfg: dict) -> np.ndarray:
    """Audio file → (T, F) features."""
    y, sr = load_audio(path)
    return extract_features(y, sr, cfg)


# ── model ─────────────────────────────────────────────────────────────────────

def make_interpreter(model_path: str | Path):
    """TFLite interpreter from ai_edge_litert / tflite_runtime / tensorflow."""
    errors = []
    for mod in ("ai_edge_litert.interpreter", "tflite_runtime.interpreter"):
        try:
            m = __import__(mod, fromlist=["Interpreter"])
            interp = m.Interpreter(model_path=str(model_path))
            interp.allocate_tensors()
            return interp, mod.split(".")[0]
        except ImportError as exc:
            errors.append(f"{mod}: {exc}")
    try:
        import tensorflow as tf  # type: ignore

        interp = tf.lite.Interpreter(model_path=str(model_path))
        interp.allocate_tensors()
        return interp, "tensorflow"
    except ImportError as exc:
        errors.append(f"tensorflow: {exc}")
    raise SystemExit(
        "No TFLite runtime found. Install one of: ai-edge-litert, tflite-runtime, "
        "tensorflow.\n  " + "\n  ".join(errors)
    )


def _qparams(detail: dict) -> tuple[float, int]:
    scale, zero = detail.get("quantization") or (0.0, 0)
    return float(scale or 0.0), int(zero or 0)


def describe(interp) -> dict:
    """Input/output tensor shape, dtype and quantization of the model."""
    def one(d):
        scale, zero = _qparams(d)
        return {
            "name": d.get("name"),
            "shape": [int(x) for x in d.get("shape", [])],
            "dtype": np.dtype(d.get("dtype")).name,
            "quantization": {"scale": scale, "zero_point": zero} if scale else None,
        }

    return {
        "inputs": [one(d) for d in interp.get_input_details()],
        "outputs": [one(d) for d in interp.get_output_details()],
    }


def to_model_input(features: np.ndarray, detail: dict) -> np.ndarray:
    """(T, F) features → model input tensor (batch/channel axes, int quantization)."""
    shape = [int(x) for x in detail["shape"]]
    x = np.asarray(features, dtype=np.float32)
    if x.ndim == 2 and len(shape) == 4:
        x = x[np.newaxis, ..., np.newaxis]  # (1, T, F, 1) like dataset_builder
    elif x.ndim == 2 and len(shape) == 3:
        x = x[np.newaxis, ...]
    if list(x.shape) != shape and int(np.prod(x.shape)) == int(np.prod(shape)):
        x = x.reshape(shape)
    if list(x.shape) != shape:
        raise ValueError(
            f"feature tensor {list(x.shape)} does not match model input {shape} — "
            "check preprocessing.json (sample_rate / hop_length / fixed_length)"
        )
    dtype = np.dtype(detail["dtype"])
    if np.issubdtype(dtype, np.integer):
        scale, zero = _qparams(detail)
        if not scale:
            scale = 1.0
        info = np.iinfo(dtype)
        x = np.clip(np.round(x / scale + zero), info.min, info.max)
    return x.astype(dtype)


def predict(interp, features: np.ndarray) -> np.ndarray:
    """Class probabilities (float32, dequantized) for one (T, F) feature matrix."""
    inp = interp.get_input_details()[0]
    out = interp.get_output_details()[0]
    interp.set_tensor(inp["index"], to_model_input(features, inp))
    interp.invoke()
    raw = interp.get_tensor(out["index"])[0]
    if np.issubdtype(np.dtype(out["dtype"]), np.integer):
        scale, zero = _qparams(out)
        raw = (raw.astype(np.float32) - zero) * (scale or 1.0)
    probs = np.asarray(raw, dtype=np.float32).reshape(-1)
    total = float(probs.sum())
    if probs.min() < -1e-3 or probs.max() > 1.0 + 1e-3 or abs(total - 1.0) > 0.1:
        e = np.exp(probs - probs.max())  # logits → probabilities
        probs = e / e.sum()
    return probs


def top_k(probs: np.ndarray, labels: list[str], k: int) -> list[dict]:
    order = np.argsort(-probs)[: max(1, k)]
    return [
        {"label": labels[i] if i < len(labels) else str(i), "index": int(i), "probability": float(probs[i])}
        for i in order
    ]


# ── CLI ───────────────────────────────────────────────────────────────────────

def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Run the packaged model on audio files.")
    ap.add_argument("audio", nargs="*", help="WAV/FLAC/OGG files (any rate; resampled like training)")
    ap.add_argument("--model", default=str(HERE / "model.tflite"))
    ap.add_argument("--labels", default=str(HERE / "labels.txt"))
    ap.add_argument("--preprocessing", default=str(HERE / "preprocessing.json"))
    ap.add_argument("--features", nargs="*", default=[], help="pre-computed (T, F) .npy feature files")
    ap.add_argument("--top-k", type=int, default=3)
    ap.add_argument("--json", action="store_true", help="machine-readable output")
    ap.add_argument("--describe", action="store_true", help="print model tensor details")
    args = ap.parse_args(argv)

    cfg = load_preprocessing(Path(args.preprocessing))
    labels = load_labels(cfg, Path(args.labels))
    if not (args.audio or args.features or args.describe):
        ap.error("give at least one audio file (or --features / --describe)")

    interp, runtime = make_interpreter(args.model)
    report: dict = {"runtime": runtime, "results": []}
    if args.describe:
        report["model"] = describe(interp)
        report["preprocessing"] = {k: cfg.get(k) for k in ("features", "frames", "input") if k in cfg}

    jobs = [("audio", a) for a in args.audio] + [("features", f) for f in args.features]
    for kind, src in jobs:
        try:
            feats = preprocess_file(src, cfg) if kind == "audio" else np.load(src)
            probs = predict(interp, feats)
            report["results"].append({
                "file": str(src),
                "feature_shape": list(np.shape(feats)),
                "top": top_k(probs, labels, args.top_k),
                "probabilities": [float(p) for p in probs],
            })
        except Exception as exc:  # keep going over a batch of files
            report["results"].append({"file": str(src), "error": f"{type(exc).__name__}: {exc}"})

    if args.json:
        print(json.dumps(report, indent=2))
    else:
        if args.describe:
            print(json.dumps(report["model"], indent=2))
        for row in report["results"]:
            if "error" in row:
                print(f"{row['file']}: ERROR {row['error']}")
                continue
            best = row["top"][0]
            others = ", ".join(f"{t['label']} {t['probability']:.3f}" for t in row["top"][1:])
            print(f"{row['file']}: {best['label']} ({best['probability']:.3f})" + (f"  [{others}]" if others else ""))
    return 1 if any("error" in r for r in report["results"]) else 0


if __name__ == "__main__":
    sys.exit(main())
