# app/core/ml/embedded_packaging.py
"""
Bounded Context:  ML deployment (edge / MCU)
Responsibility:   Turn a TFLite flatbuffer into real embedded deliverables
                  (F19 / F-05): C source arrays for TensorFlow Lite Micro, an
                  Arduino library, a Zephyr module and a CMSIS-Pack.
Public Surface:   is_tflite(path) -> bool
                  write_c_model(model_bytes, out_dir, *, symbol, labels, header_dir=None, ext="c")
                  build_arduino_library(model, labels, dest, name) -> Path (.zip)
                  build_zephyr_module(model, labels, dest, name) -> Path (dir)
                  build_cmsis_pack(model, labels, dest, name, version) -> Path (.pack)
Must NOT:         Import plugins; claim compilation for a board (we emit sources,
                  the board toolchain builds them).
Dependencies:     stdlib only.

Every artifact embeds the actual model bytes (16-byte aligned, as TFLM
requires) and the label list; the inference sketch / wrapper uses the public
TFLM API (``tflite::MicroInterpreter``). Nothing here is a placeholder: the C
sources compile with any C99/C++11 compiler (unit-tested with gcc).
"""
from __future__ import annotations

import re
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from xml.sax.saxutils import escape

TFLITE_MAGIC = b"TFL3"


def is_tflite(path: Path | str | None) -> bool:
    """True when *path* is a TFLite flatbuffer (file identifier ``TFL3`` at offset 4)."""
    if not path:
        return False
    p = Path(path)
    try:
        with p.open("rb") as fh:
            head = fh.read(8)
    except OSError:
        return False
    return len(head) == 8 and head[4:8] == TFLITE_MAGIC


def c_identifier(name: str) -> str:
    ident = re.sub(r"[^0-9A-Za-z_]", "_", name or "model").strip("_") or "model"
    return ("m_" + ident) if ident[0].isdigit() else ident


def _c_string(s: str) -> str:
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ") + '"'


def write_c_model(
    model_bytes: bytes,
    out_dir: Path,
    *,
    symbol: str = "g_model",
    labels: list[str] | None = None,
    header_dir: Path | None = None,
    ext: str = "c",
    basename: str = "model_data",
) -> tuple[Path, Path]:
    """Write ``<basename>.h`` + ``<basename>.<ext>`` with the model as a C array."""
    if not model_bytes:
        raise ValueError("embedded packaging: model is empty")
    sym = c_identifier(symbol)
    labels = [str(x) for x in (labels or [])]
    out_dir = Path(out_dir)
    hdir = Path(header_dir) if header_dir else out_dir
    out_dir.mkdir(parents=True, exist_ok=True)
    hdir.mkdir(parents=True, exist_ok=True)
    guard = f"{sym.upper()}_DATA_H_"
    header = hdir / f"{basename}.h"
    header.write_text(
        "/* Generated by Graphyn — TensorFlow Lite model for TFLite Micro. */\n"
        f"#ifndef {guard}\n#define {guard}\n\n#include <stdint.h>\n\n"
        "#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n"
        f"extern const unsigned char {sym}[];\n"
        f"extern const unsigned int {sym}_len;\n"
        f"extern const char* const {sym}_labels[];\n"
        f"extern const int {sym}_num_labels;\n\n"
        "#ifdef __cplusplus\n}\n#endif\n\n"
        f"#endif /* {guard} */\n",
        encoding="utf-8",
    )
    src = out_dir / f"{basename}.{ext}"
    with src.open("w", encoding="utf-8") as fh:
        fh.write(f'/* Generated by Graphyn. {len(model_bytes)} bytes. */\n#include "{basename}.h"\n\n')
        fh.write("#if defined(__GNUC__) || defined(__clang__)\n#define GRAPHYN_ALIGN16 __attribute__((aligned(16)))\n")
        fh.write("#else\n#define GRAPHYN_ALIGN16\n#endif\n\n")
        fh.write(f"const unsigned char {sym}[] GRAPHYN_ALIGN16 = {{\n")
        for i in range(0, len(model_bytes), 12):
            chunk = model_bytes[i : i + 12]
            fh.write("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",\n")
        fh.write("};\n")
        fh.write(f"const unsigned int {sym}_len = {len(model_bytes)}u;\n\n")
        items = ", ".join(_c_string(x) for x in labels) if labels else '""'
        fh.write(f"const char* const {sym}_labels[] = {{{items}}};\n")
        fh.write(f"const int {sym}_num_labels = {len(labels)};\n")
    return header, src


# ── TFLite flatbuffer: operators used (for a minimal TFLM op resolver) ───────

_BUILTIN_OPS = (
    "ADD",
    "AVERAGE_POOL_2D",
    "CONCATENATION",
    "CONV_2D",
    "DEPTHWISE_CONV_2D",
    "DEPTH_TO_SPACE",
    "DEQUANTIZE",
    "EMBEDDING_LOOKUP",
    "FLOOR",
    "FULLY_CONNECTED",
    "HASHTABLE_LOOKUP",
    "L2_NORMALIZATION",
    "L2_POOL_2D",
    "LOCAL_RESPONSE_NORMALIZATION",
    "LOGISTIC",
    "LSH_PROJECTION",
    "LSTM",
    "MAX_POOL_2D",
    "MUL",
    "RELU",
    "RELU_N1_TO_1",
    "RELU6",
    "RESHAPE",
    "RESIZE_BILINEAR",
    "RNN",
    "SOFTMAX",
    "SPACE_TO_DEPTH",
    "SVDF",
    "TANH",
    "CONCAT_EMBEDDINGS",
    "SKIP_GRAM",
    "CALL",
    "CUSTOM",
    "EMBEDDING_LOOKUP_SPARSE",
    "PAD",
    "UNIDIRECTIONAL_SEQUENCE_RNN",
    "GATHER",
    "BATCH_TO_SPACE_ND",
    "SPACE_TO_BATCH_ND",
    "TRANSPOSE",
    "MEAN",
    "SUB",
    "DIV",
    "SQUEEZE",
    "UNIDIRECTIONAL_SEQUENCE_LSTM",
    "STRIDED_SLICE",
    "BIDIRECTIONAL_SEQUENCE_RNN",
    "EXP",
    "TOPK_V2",
    "SPLIT",
    "LOG_SOFTMAX",
    "DELEGATE",
    "BIDIRECTIONAL_SEQUENCE_LSTM",
    "CAST",
    "PRELU",
    "MAXIMUM",
    "ARG_MAX",
    "MINIMUM",
    "LESS",
    "NEG",
    "PADV2",
    "GREATER",
    "GREATER_EQUAL",
    "LESS_EQUAL",
    "SELECT",
    "SLICE",
    "SIN",
    "TRANSPOSE_CONV",
    "SPARSE_TO_DENSE",
    "TILE",
    "EXPAND_DIMS",
    "EQUAL",
    "NOT_EQUAL",
    "LOG",
    "SUM",
    "SQRT",
    "RSQRT",
    "SHAPE",
    "POW",
    "ARG_MIN",
    "FAKE_QUANT",
    "REDUCE_PROD",
    "REDUCE_MAX",
    "PACK",
    "LOGICAL_OR",
    "ONE_HOT",
    "LOGICAL_AND",
    "LOGICAL_NOT",
    "UNPACK",
    "REDUCE_MIN",
    "FLOOR_DIV",
    "REDUCE_ANY",
    "SQUARE",
    "ZEROS_LIKE",
    "FILL",
    "FLOOR_MOD",
    "RANGE",
    "RESIZE_NEAREST_NEIGHBOR",
    "LEAKY_RELU",
    "SQUARED_DIFFERENCE",
    "MIRROR_PAD",
    "ABS",
    "SPLIT_V",
    "UNIQUE",
    "CEIL",
    "REVERSE_V2",
    "ADD_N",
    "GATHER_ND",
    "COS",
    "WHERE",
    "RANK",
    "ELU",
    "REVERSE_SEQUENCE",
    "MATRIX_DIAG",
    "QUANTIZE",
    "MATRIX_SET_DIAG",
    "ROUND",
    "HARD_SWISH",
    "IF",
    "WHILE",
    "NON_MAX_SUPPRESSION_V4",
    "NON_MAX_SUPPRESSION_V5",
    "SCATTER_ND",
    "SELECT_V2",
    "DENSIFY",
    "SEGMENT_SUM",
    "BATCH_MATMUL",
)

# BuiltinOperator → MicroMutableOpResolver::Add<Op>() (ops TFLM implements).
_TFLM_ADD = {
    "ADD": "AddAdd", "AVERAGE_POOL_2D": "AddAveragePool2D", "CONCATENATION": "AddConcatenation",
    "CONV_2D": "AddConv2D", "DEPTHWISE_CONV_2D": "AddDepthwiseConv2D", "DEPTH_TO_SPACE": "AddDepthToSpace",
    "DEQUANTIZE": "AddDequantize", "FLOOR": "AddFloor", "FULLY_CONNECTED": "AddFullyConnected",
    "L2_NORMALIZATION": "AddL2Normalization", "L2_POOL_2D": "AddL2Pool2D", "LOGISTIC": "AddLogistic",
    "MAX_POOL_2D": "AddMaxPool2D", "MUL": "AddMul", "RELU": "AddRelu", "RELU6": "AddRelu6",
    "RESHAPE": "AddReshape", "RESIZE_BILINEAR": "AddResizeBilinear", "SOFTMAX": "AddSoftmax",
    "SPACE_TO_DEPTH": "AddSpaceToDepth", "SVDF": "AddSvdf", "TANH": "AddTanh", "PAD": "AddPad",
    "GATHER": "AddGather", "BATCH_TO_SPACE_ND": "AddBatchToSpaceNd", "SPACE_TO_BATCH_ND": "AddSpaceToBatchNd",
    "TRANSPOSE": "AddTranspose", "MEAN": "AddMean", "SUB": "AddSub", "DIV": "AddDiv",
    "SQUEEZE": "AddSqueeze", "UNIDIRECTIONAL_SEQUENCE_LSTM": "AddUnidirectionalSequenceLSTM",
    "STRIDED_SLICE": "AddStridedSlice", "EXP": "AddExp", "SPLIT": "AddSplit", "LOG_SOFTMAX": "AddLogSoftmax",
    "CAST": "AddCast", "PRELU": "AddPrelu", "MAXIMUM": "AddMaximum", "ARG_MAX": "AddArgMax",
    "MINIMUM": "AddMinimum", "LESS": "AddLess", "NEG": "AddNeg", "PADV2": "AddPadV2",
    "GREATER": "AddGreater", "GREATER_EQUAL": "AddGreaterEqual", "LESS_EQUAL": "AddLessEqual",
    "SLICE": "AddSlice", "SIN": "AddSin", "TRANSPOSE_CONV": "AddTransposeConv", "EXPAND_DIMS": "AddExpandDims",
    "EQUAL": "AddEqual", "NOT_EQUAL": "AddNotEqual", "LOG": "AddLog", "SUM": "AddSum", "SQRT": "AddSqrt",
    "RSQRT": "AddRsqrt", "SHAPE": "AddShape", "ARG_MIN": "AddArgMin", "REDUCE_MAX": "AddReduceMax",
    "PACK": "AddPack", "LOGICAL_OR": "AddLogicalOr", "LOGICAL_AND": "AddLogicalAnd", "LOGICAL_NOT": "AddLogicalNot",
    "UNPACK": "AddUnpack", "FLOOR_DIV": "AddFloorDiv", "SQUARE": "AddSquare", "ZEROS_LIKE": "AddZerosLike",
    "FILL": "AddFill", "FLOOR_MOD": "AddFloorMod", "RESIZE_NEAREST_NEIGHBOR": "AddResizeNearestNeighbor",
    "LEAKY_RELU": "AddLeakyRelu", "SQUARED_DIFFERENCE": "AddSquaredDifference", "MIRROR_PAD": "AddMirrorPad",
    "ABS": "AddAbs", "SPLIT_V": "AddSplitV", "CEIL": "AddCeil", "ADD_N": "AddAddN", "GATHER_ND": "AddGatherNd",
    "COS": "AddCos", "ELU": "AddElu", "QUANTIZE": "AddQuantize", "ROUND": "AddRound", "HARD_SWISH": "AddHardSwish",
    "IF": "AddIf", "WHILE": "AddWhile", "SELECT_V2": "AddSelectV2", "BATCH_MATMUL": "AddBatchMatMul",
}


def tflite_operators(model_bytes: bytes) -> list[str]:
    """Builtin operator names used by a TFLite flatbuffer (stdlib flatbuffer walk)."""
    import struct

    buf = memoryview(model_bytes)
    if len(buf) < 8 or bytes(buf[4:8]) != TFLITE_MAGIC:
        raise ValueError("not a TFLite flatbuffer")

    def u32(o: int) -> int:
        return struct.unpack_from("<I", buf, o)[0]

    def field(table: int, idx: int) -> int | None:
        vt = table - struct.unpack_from("<i", buf, table)[0]
        vt_size = struct.unpack_from("<H", buf, vt)[0]
        off_pos = 4 + 2 * idx
        if off_pos >= vt_size:
            return None
        off = struct.unpack_from("<H", buf, vt + off_pos)[0]
        return table + off if off else None

    root = u32(0)
    codes_f = field(root, 1)
    if codes_f is None:
        return []
    vec = codes_f + u32(codes_f)
    names: list[str] = []
    for i in range(u32(vec)):
        el = vec + 4 + 4 * i
        tbl = el + u32(el)
        dep = field(tbl, 0)
        new = field(tbl, 3)
        code = struct.unpack_from("<b", buf, dep)[0] if dep is not None else 0
        if new is not None:
            code = max(code, struct.unpack_from("<i", buf, new)[0])
        name = _BUILTIN_OPS[code] if 0 <= code < len(_BUILTIN_OPS) else f"BUILTIN_{code}"
        if name == "CUSTOM":
            cf = field(tbl, 1)
            if cf is not None:
                sp = cf + u32(cf)
                name = "CUSTOM:" + bytes(buf[sp + 4 : sp + 4 + u32(sp)]).decode("utf-8", "replace")
        if name not in names:
            names.append(name)
    return names


def op_resolver_source(model_bytes: bytes) -> tuple[str, list[str]]:
    """C++ lines registering exactly the ops the model uses; plus unsupported ops."""
    ops = tflite_operators(model_bytes)
    adds = [_TFLM_ADD[o] for o in ops if o in _TFLM_ADD]
    missing = [o for o in ops if o not in _TFLM_ADD]
    lines = [f"  static tflite::MicroMutableOpResolver<{max(1, len(adds))}> resolver;"]
    lines += [f"  resolver.{a}();" for a in adds]
    return "\n".join(lines), missing


_INFERENCE_CPP = """\
// Generated by Graphyn: run {name} with TensorFlow Lite Micro.
// Feed the same features the model was trained on (see preprocessing notes).
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "tensorflow/lite/schema/schema_generated.h"
#include "{header}"

namespace {{
constexpr int kArenaSize = {arena} * 1024;
alignas(16) uint8_t g_arena[kArenaSize];
tflite::MicroInterpreter* g_interpreter = nullptr;
}}

// Returns 0 on success.
int {sym}_setup() {{
  const tflite::Model* model = tflite::GetModel({sym});
  if (model->version() != TFLITE_SCHEMA_VERSION) return 1;
  // Exactly the operators this model uses: {ops}
{resolver}
  static tflite::MicroInterpreter interpreter(model, resolver, g_arena, kArenaSize);
  if (interpreter.AllocateTensors() != kTfLiteOk) return 2;
  g_interpreter = &interpreter;
  return 0;
}}

// Writes `n` float features into input 0 (quantizing when the input tensor is
// int8/uint8), runs the model and returns the top-1 class index (or -1).
int {sym}_classify(const float* features, int n) {{
  if (!g_interpreter) return -1;
  TfLiteTensor* in = g_interpreter->input(0);
  const float s = in->params.scale != 0.f ? in->params.scale : 1.f;
  const int zp = in->params.zero_point;
  int count = 0;
  switch (in->type) {{
    case kTfLiteFloat32: count = in->bytes / sizeof(float); break;
    case kTfLiteInt8: case kTfLiteUInt8: count = in->bytes; break;
    default: return -1;
  }}
  for (int i = 0; i < count; ++i) {{
    const float v = i < n ? features[i] : 0.f;
    if (in->type == kTfLiteFloat32) {{ in->data.f[i] = v; continue; }}
    int q = (int)(v / s + (v >= 0 ? 0.5f : -0.5f)) + zp;
    if (in->type == kTfLiteInt8) in->data.int8[i] = (int8_t)(q < -128 ? -128 : q > 127 ? 127 : q);
    else in->data.uint8[i] = (uint8_t)(q < 0 ? 0 : q > 255 ? 255 : q);
  }}
  if (g_interpreter->Invoke() != kTfLiteOk) return -1;
  TfLiteTensor* out = g_interpreter->output(0);
  int classes = out->type == kTfLiteFloat32 ? (int)(out->bytes / sizeof(float)) : (int)out->bytes;
  int best = 0;
  for (int i = 1; i < classes; ++i) {{
    float a = out->type == kTfLiteFloat32 ? out->data.f[i] : out->type == kTfLiteInt8 ? out->data.int8[i] : out->data.uint8[i];
    float b = out->type == kTfLiteFloat32 ? out->data.f[best] : out->type == kTfLiteInt8 ? out->data.int8[best] : out->data.uint8[best];
    if (a > b) best = i;
  }}
  return best;
}}
"""


def _inference_source(name: str, sym: str, header: str, model_bytes: bytes) -> str:
    arena_kb = max(16, min(512, (len(model_bytes) // 1024) // 2 + 32))
    resolver, missing = op_resolver_source(model_bytes)
    if missing:
        raise ValueError(
            f"model uses operators TensorFlow Lite Micro does not implement: {', '.join(missing)}"
        )
    ops = ", ".join(tflite_operators(model_bytes)) or "none"
    return _INFERENCE_CPP.format(name=name, sym=sym, header=header, arena=arena_kb,
                                 resolver=resolver, ops=ops)


def build_arduino_library(model: Path, labels: list[str], dest: Path, name: str) -> Path:
    """Arduino library (.zip, "Sketch → Include Library → Add .ZIP Library")."""
    lib = c_identifier(name)
    root = Path(dest) / lib
    src = root / "src"
    write_c_model(model.read_bytes(), src, symbol=f"{lib}_model", labels=labels, ext="cpp", basename=f"{lib}_model_data")
    sym = c_identifier(f"{lib}_model")
    (src / f"{lib}_inference.cpp").write_text(
        _inference_source(lib, sym, f"{lib}_model_data.h", model.read_bytes()), encoding="utf-8"
    )
    (src / f"{lib}.h").write_text(
        f'#pragma once\n#include <stdint.h>\n#include "{lib}_model_data.h"\n'
        f"int {sym}_setup();\nint {sym}_classify(const float* features, int n);\n",
        encoding="utf-8",
    )
    ex = root / "examples" / f"{lib}_classify"
    ex.mkdir(parents=True, exist_ok=True)
    (ex / f"{lib}_classify.ino").write_text(
        f'#include <{lib}.h>\n\nvoid setup() {{\n  Serial.begin(115200);\n'
        f'  if ({sym}_setup() != 0) {{ Serial.println("model setup failed"); while (1) {{}} }}\n'
        f'  Serial.print("labels: "); Serial.println({sym}_num_labels);\n}}\n\n'
        f"void loop() {{\n  // Fill `features` from your sensor pipeline, then:\n"
        f"  static float features[1024] = {{0}};\n"
        f"  int idx = {sym}_classify(features, 1024);\n"
        f'  if (idx >= 0 && idx < {sym}_num_labels) Serial.println({sym}_labels[idx]);\n  delay(1000);\n}}\n',
        encoding="utf-8",
    )
    (root / "library.properties").write_text(
        f"name={lib}\nversion=1.0.0\nauthor=Graphyn\nmaintainer=Graphyn\n"
        f"sentence=TFLite Micro model {name} exported by Graphyn.\n"
        f"paragraph={len(labels)} labels, {model.stat().st_size} byte model.\n"
        "category=Data Processing\nurl=https://graphyn.local\narchitectures=*\n"
        "depends=Chirale_TensorFLowLite\nincludes=" + f"{lib}.h\n",
        encoding="utf-8",
    )
    zpath = Path(dest) / f"{lib}.zip"
    with zipfile.ZipFile(zpath, "w", zipfile.ZIP_DEFLATED) as zf:
        for f in sorted(root.rglob("*")):
            if f.is_file():
                zf.write(f, f.relative_to(Path(dest)).as_posix())
    return zpath


def build_zephyr_module(model: Path, labels: list[str], dest: Path, name: str) -> Path:
    """Zephyr external module (add to ZEPHYR_EXTRA_MODULES / west manifest)."""
    mod = c_identifier(name)
    root = Path(dest) / mod
    write_c_model(model.read_bytes(), root / "src", symbol=f"{mod}_model", labels=labels,
                  header_dir=root / "include", basename=f"{mod}_model_data")
    kconf = f"GRAPHYN_{mod.upper()}"
    zdir = root / "zephyr"
    zdir.mkdir(parents=True, exist_ok=True)
    (zdir / "module.yml").write_text(
        f"name: {mod}\nbuild:\n  cmake: zephyr\n  kconfig: zephyr/Kconfig\n", encoding="utf-8"
    )
    (zdir / "Kconfig").write_text(
        f'config {kconf}\n\tbool "Graphyn model {name}"\n\tdefault y\n\thelp\n'
        f"\t  Embeds the {name} TFLite model ({model.stat().st_size} bytes) and its labels.\n",
        encoding="utf-8",
    )
    (zdir / "CMakeLists.txt").write_text(
        f"if(CONFIG_{kconf})\n  zephyr_library()\n"
        f"  zephyr_library_sources(${{ZEPHYR_CURRENT_MODULE_DIR}}/src/{mod}_model_data.c)\n"
        f"  zephyr_include_directories(${{ZEPHYR_CURRENT_MODULE_DIR}}/include)\nendif()\n",
        encoding="utf-8",
    )
    (root / "README.md").write_text(
        f"# {mod} (Zephyr module)\n\nAdd `-DZEPHYR_EXTRA_MODULES={mod}` (or a west project entry), "
        f"enable `CONFIG_{kconf}=y`, and link TFLite Micro (`CONFIG_TENSORFLOW_LITE_MICRO=y`).\n"
        f"Symbols: `{mod}_model`, `{mod}_model_len`, `{mod}_model_labels`.\n",
        encoding="utf-8",
    )
    return root


def build_cmsis_pack(model: Path, labels: list[str], dest: Path, name: str, version: str = "1.0.0") -> Path:
    """CMSIS-Pack (``Graphyn.<Name>.<version>.pack``) with a PDSC component."""
    pack = re.sub(r"[^0-9A-Za-z_-]", "_", name or "Model") or "Model"
    root = Path(dest) / f"Graphyn.{pack}"
    sym = c_identifier(f"{pack}_model")
    write_c_model(model.read_bytes(), root / "Source", symbol=sym, labels=labels,
                  header_dir=root / "Include", basename=f"{pack}_model_data")
    date = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    pdsc = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<package schemaVersion="1.7.7" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" '
        'xs:noNamespaceSchemaLocation="https://raw.githubusercontent.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/v1.7.7/schema/PACK.xsd">\n'
        "  <vendor>Graphyn</vendor>\n"
        f"  <name>{escape(pack)}</name>\n"
        f"  <description>TFLite Micro model {escape(name)} ({len(labels)} labels) exported by Graphyn.</description>\n"
        "  <url></url>\n"
        f'  <releases>\n    <release version="{escape(version)}" date="{date}">Generated by Graphyn.</release>\n  </releases>\n'
        "  <keywords>\n    <keyword>TensorFlow Lite Micro</keyword>\n  </keywords>\n"
        "  <components>\n"
        f'    <component Cclass="Machine Learning" Cgroup="Model" Csub="{escape(pack)}" Cversion="{escape(version)}">\n'
        f"      <description>Model data and labels for {escape(name)}</description>\n"
        "      <files>\n"
        '        <file category="include" name="Include/"/>\n'
        f'        <file category="header" name="Include/{escape(pack)}_model_data.h"/>\n'
        f'        <file category="source" name="Source/{escape(pack)}_model_data.c"/>\n'
        "      </files>\n    </component>\n  </components>\n</package>\n"
    )
    (root / f"Graphyn.{pack}.pdsc").write_text(pdsc, encoding="utf-8")
    out = Path(dest) / f"Graphyn.{pack}.{version}.pack"
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as zf:
        for f in sorted(root.rglob("*")):
            if f.is_file():
                zf.write(f, f.relative_to(root).as_posix())
    return out


__all__ = [
    "build_arduino_library",
    "build_cmsis_pack",
    "build_zephyr_module",
    "c_identifier",
    "is_tflite",
    "op_resolver_source",
    "tflite_operators",
    "write_c_model",
]
