# app/mcp/handlers/journey/__init__.py
"""
Bounded Context:  Application Layer — MCP Interface
Responsibility:   Re-export journey MCP handlers so tool_registry keeps one import path.
Owns:             Public names of the journey submodules.
Public Surface:   from app.mcp.handlers.journey import <handler or schema>
Must NOT:         Add handler logic here.
Dependencies:     app.mcp.handlers.journey.*
Reason To Change: A journey tool moves to a new submodule.
"""
from __future__ import annotations

from app.mcp.handlers.journey.pipelines import (
    LIST_PIPELINES_DESCRIPTION,
    LIST_PIPELINES_SCHEMA,
    GET_PIPELINE_DESCRIPTION,
    GET_PIPELINE_SCHEMA,
    SAVE_PIPELINE_DESCRIPTION,
    SAVE_PIPELINE_SCHEMA,
    PUBLISH_PIPELINE_DESCRIPTION,
    PUBLISH_PIPELINE_SCHEMA,
    PROMOTE_PIPELINE_DESCRIPTION,
    PROMOTE_PIPELINE_SCHEMA,
    ROLLBACK_PIPELINE_DESCRIPTION,
    ROLLBACK_PIPELINE_SCHEMA,
    list_pipelines_handler,
    get_pipeline_handler,
    save_pipeline_handler,
    publish_pipeline_handler,
    promote_pipeline_handler,
    rollback_pipeline_handler,
)

from app.mcp.handlers.journey.runs import (
    LIST_RUNS_DESCRIPTION,
    LIST_RUNS_SCHEMA,
    GET_RUN_DESCRIPTION,
    GET_RUN_SCHEMA,
    GET_RUN_OUTPUTS_DESCRIPTION,
    GET_RUN_OUTPUTS_SCHEMA,
    list_runs_handler,
    get_run_handler,
    get_run_outputs_handler,
    COMPARE_RUNS_DESCRIPTION,
    COMPARE_RUNS_SCHEMA,
    compare_runs_handler,
)

from app.mcp.handlers.journey.templates import (
    LIST_TEMPLATES_DESCRIPTION,
    LIST_TEMPLATES_SCHEMA,
    GET_TEMPLATE_DESCRIPTION,
    GET_TEMPLATE_SCHEMA,
    INSTANTIATE_TEMPLATE_DESCRIPTION,
    INSTANTIATE_TEMPLATE_SCHEMA,
    list_templates_handler,
    get_template_handler,
    instantiate_template_handler,
    SEARCH_TEMPLATES_DESCRIPTION,
    SEARCH_TEMPLATES_SCHEMA,
    search_templates_handler,
)

from app.mcp.handlers.journey.models import (
    LIST_MODELS_DESCRIPTION,
    LIST_MODELS_SCHEMA,
    GET_MODEL_DESCRIPTION,
    GET_MODEL_SCHEMA,
    REGISTER_MODEL_DESCRIPTION,
    REGISTER_MODEL_SCHEMA,
    REQUEST_MODEL_PROD_DESCRIPTION,
    REQUEST_MODEL_PROD_SCHEMA,
    APPROVE_MODEL_PROD_DESCRIPTION,
    APPROVE_MODEL_PROD_SCHEMA,
    list_models_handler,
    get_model_handler,
    register_model_handler,
    request_model_prod_handler,
    approve_model_prod_handler,
)

from app.mcp.handlers.journey.schedules import (
    LIST_SCHEDULES_DESCRIPTION,
    LIST_SCHEDULES_SCHEMA,
    UPSERT_SCHEDULE_DESCRIPTION,
    UPSERT_SCHEDULE_SCHEMA,
    ENABLE_SCHEDULE_DESCRIPTION,
    ENABLE_SCHEDULE_SCHEMA,
    DELETE_SCHEDULE_DESCRIPTION,
    DELETE_SCHEDULE_SCHEMA,
    RUN_SCHEDULE_NOW_DESCRIPTION,
    RUN_SCHEDULE_NOW_SCHEMA,
    GET_WEBHOOKS_DESCRIPTION,
    GET_WEBHOOKS_SCHEMA,
    PUT_WEBHOOKS_DESCRIPTION,
    PUT_WEBHOOKS_SCHEMA,
    TEST_WEBHOOK_DESCRIPTION,
    TEST_WEBHOOK_SCHEMA,
    list_schedules_handler,
    upsert_schedule_handler,
    enable_schedule_handler,
    delete_schedule_handler,
    run_schedule_now_handler,
    get_webhooks_handler,
    put_webhooks_handler,
    test_webhook_handler,
)

from app.mcp.handlers.journey.readiness import (
    GET_READINESS_DESCRIPTION,
    GET_READINESS_SCHEMA,
    get_readiness_handler,
)

from app.mcp.handlers.journey.catalog import (
    MATERIALIZE_TEMPLATE_DESCRIPTION,
    MATERIALIZE_TEMPLATE_SCHEMA,
    materialize_template_handler,
    GET_NODE_SPEC_DESCRIPTION,
    GET_NODE_SPEC_SCHEMA,
    get_node_spec_handler,
    LIST_PACKS_DESCRIPTION,
    LIST_PACKS_SCHEMA,
    list_packs_handler,
    DESCRIBE_PACK_DESCRIPTION,
    DESCRIBE_PACK_SCHEMA,
    describe_pack_handler,
)

from app.mcp.handlers.journey.notifications import (
    LIST_NOTIFICATIONS_DESCRIPTION,
    LIST_NOTIFICATIONS_SCHEMA,
    MARK_NOTIFICATIONS_READ_DESCRIPTION,
    MARK_NOTIFICATIONS_READ_SCHEMA,
    list_notifications_handler,
    mark_notifications_read_handler,
)

__all__ = [
    'LIST_PIPELINES_DESCRIPTION',
    'LIST_PIPELINES_SCHEMA',
    'GET_PIPELINE_DESCRIPTION',
    'GET_PIPELINE_SCHEMA',
    'SAVE_PIPELINE_DESCRIPTION',
    'SAVE_PIPELINE_SCHEMA',
    'PUBLISH_PIPELINE_DESCRIPTION',
    'PUBLISH_PIPELINE_SCHEMA',
    'PROMOTE_PIPELINE_DESCRIPTION',
    'PROMOTE_PIPELINE_SCHEMA',
    'ROLLBACK_PIPELINE_DESCRIPTION',
    'ROLLBACK_PIPELINE_SCHEMA',
    'list_pipelines_handler',
    'get_pipeline_handler',
    'save_pipeline_handler',
    'publish_pipeline_handler',
    'promote_pipeline_handler',
    'rollback_pipeline_handler',
    'LIST_RUNS_DESCRIPTION',
    'LIST_RUNS_SCHEMA',
    'GET_RUN_DESCRIPTION',
    'GET_RUN_SCHEMA',
    'GET_RUN_OUTPUTS_DESCRIPTION',
    'GET_RUN_OUTPUTS_SCHEMA',
    'list_runs_handler',
    'get_run_handler',
    'get_run_outputs_handler',
    'LIST_TEMPLATES_DESCRIPTION',
    'LIST_TEMPLATES_SCHEMA',
    'GET_TEMPLATE_DESCRIPTION',
    'GET_TEMPLATE_SCHEMA',
    'INSTANTIATE_TEMPLATE_DESCRIPTION',
    'INSTANTIATE_TEMPLATE_SCHEMA',
    'list_templates_handler',
    'get_template_handler',
    'instantiate_template_handler',
    'SEARCH_TEMPLATES_DESCRIPTION',
    'SEARCH_TEMPLATES_SCHEMA',
    'search_templates_handler',
    'LIST_MODELS_DESCRIPTION',
    'LIST_MODELS_SCHEMA',
    'GET_MODEL_DESCRIPTION',
    'GET_MODEL_SCHEMA',
    'REGISTER_MODEL_DESCRIPTION',
    'REGISTER_MODEL_SCHEMA',
    'REQUEST_MODEL_PROD_DESCRIPTION',
    'REQUEST_MODEL_PROD_SCHEMA',
    'APPROVE_MODEL_PROD_DESCRIPTION',
    'APPROVE_MODEL_PROD_SCHEMA',
    'COMPARE_RUNS_DESCRIPTION',
    'COMPARE_RUNS_SCHEMA',
    'list_models_handler',
    'get_model_handler',
    'register_model_handler',
    'request_model_prod_handler',
    'approve_model_prod_handler',
    'compare_runs_handler',
    'LIST_SCHEDULES_DESCRIPTION',
    'LIST_SCHEDULES_SCHEMA',
    'UPSERT_SCHEDULE_DESCRIPTION',
    'UPSERT_SCHEDULE_SCHEMA',
    'ENABLE_SCHEDULE_DESCRIPTION',
    'ENABLE_SCHEDULE_SCHEMA',
    'DELETE_SCHEDULE_DESCRIPTION',
    'DELETE_SCHEDULE_SCHEMA',
    'RUN_SCHEDULE_NOW_DESCRIPTION',
    'RUN_SCHEDULE_NOW_SCHEMA',
    'GET_WEBHOOKS_DESCRIPTION',
    'GET_WEBHOOKS_SCHEMA',
    'PUT_WEBHOOKS_DESCRIPTION',
    'PUT_WEBHOOKS_SCHEMA',
    'TEST_WEBHOOK_DESCRIPTION',
    'TEST_WEBHOOK_SCHEMA',
    'list_schedules_handler',
    'upsert_schedule_handler',
    'enable_schedule_handler',
    'delete_schedule_handler',
    'run_schedule_now_handler',
    'get_webhooks_handler',
    'put_webhooks_handler',
    'test_webhook_handler',
    'GET_READINESS_DESCRIPTION',
    'GET_READINESS_SCHEMA',
    'get_readiness_handler',
    'MATERIALIZE_TEMPLATE_DESCRIPTION',
    'MATERIALIZE_TEMPLATE_SCHEMA',
    'materialize_template_handler',
    'GET_NODE_SPEC_DESCRIPTION',
    'GET_NODE_SPEC_SCHEMA',
    'get_node_spec_handler',
    'LIST_PACKS_DESCRIPTION',
    'LIST_PACKS_SCHEMA',
    'list_packs_handler',
    'DESCRIBE_PACK_DESCRIPTION',
    'DESCRIBE_PACK_SCHEMA',
    'describe_pack_handler',
    'LIST_NOTIFICATIONS_DESCRIPTION',
    'LIST_NOTIFICATIONS_SCHEMA',
    'MARK_NOTIFICATIONS_READ_DESCRIPTION',
    'MARK_NOTIFICATIONS_READ_SCHEMA',
    'list_notifications_handler',
    'mark_notifications_read_handler',
]
